usethis::use_build_ignore("devtools_history.R")
usethis::use_package("stats")
devtools::install_github("r-lib/testthat")
usethis::use_package("questionr")
usethis::use_package("ade4")
usethis::use_package("FactoMineR")
usethis::use_package("factoextra")
usethis::use_package("ggplot2")
usethis::use_package("dplyr")
usethis::use_package("stats")
usethis::use_package("utils")
usethis::use_package("PerformanceAnalytics")
usethis::use_package("corrplot")
usethis::use_package("ggpubr")
usethis::use_package("ExPosition")
usethis::use_package("graphics")
BankCustomer <- read.csv("C:/Users/adrien/Documents/Test_data/BankCustomer.csv", sep=";", dec=",")
usethis::use_data(BankCustomer)
